---
- name: Copying files from controller to hosts
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: true # default is true

       
  tasks:

  - name: create  directories
    become_user: root
    become: true
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user_gid }}"
      mode: "0755"
    loop: [lennon,macartney,starr,harrison]



