---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ansible.builtin.ssh

  tasks:
   - name: make a directory
     ansible.builtin.file:
       path: ~/output/
       state: directory


   - name: create ~/output/path.txt file 
     ansible.builtin.copy:
       dest: ~/output/path.txt
       content: "{{ ansible_env.HOME }}"



