---
- name: Debug playbook to display ansible facts
  hosts: planetexpress
  gather_facts: yes

  tasks:
    # package attempts to identify the package handler on the local system
    # and use the correct module
    # however each repo may name package in a unique manner so you still
    # may with to limit a task with the when: ansible_distribution conditional
    # examples: yum, apt, dnf, pkg, etc.
    - name: Install an app with apt only on Ubuntu systems
      package:
        state: absent
        name: sl
      when: ansible_distribution == "CentOS"
      become: yes

    # print out the value of ansible_distribution_version
    - name: Print out both users distro ver
      debug:
        var: ansible_facts

